# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2

project_name: lpgw

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/lpgw
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    flags:
      - -trimpath
    ldflags:
      - -s -w

archives:
  - formats: [tar.gz]

checksum:
  name_template: checksums.txt

sboms:
  - artifacts: archive

changelog:
  disable: true
